lang: en
logo:
    $link: logo.svg
repo: https://github.com/atomicojs/atomicojs.github.io/tree/master
socials:
    github: uppercod/estack
    twitter: uppercod
menu:
    - title:
          es: Documentación
          en: Documentation
      category: aside
aside:
    content:
        title: Contenido
