message1:
    $ref: message.txt
message2:
    $ref: message.txt
user:
    $ref: https://jsonplaceholder.typicode.com/users
langs:
    - link: ./docs/stylis/stylis.md
    - link: ./docs/rollup/rollup.md
