name: deploy

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Node install
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - run: npm install
            - run: npm run build:site

            - name: Commit and push
              uses: EndBug/add-and-commit@v4
              with:
                  author_name: uppercod
                  author_email: mtrujillo@outlook.cl
                  message: "Build files"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
